
/* =====================================================
   CIVICLENS FRONTEND
===================================================== */


/* =====================================================
   CONFIGURATION
===================================================== */

const API_BASE_URL = "http://127.0.0.1:8000";


/*
   IMPORTANT:

   JWT_SECRET_KEY NEVER goes here.

   The JWT secret stays inside your backend .env file.

   The frontend should only receive/use the JWT token
   generated by the backend after successful login.
*/


/* =====================================================
   PAKISTAN CITIES
===================================================== */

const pakistanCities = [

    "Islamabad",
    "Rawalpindi",
    "Lahore",
    "Karachi",
    "Peshawar",
    "Quetta",
    "Multan",
    "Faisalabad",
    "Gujranwala",
    "Sialkot",
    "Hyderabad",
    "Bahawalpur",
    "Sargodha",
    "Sukkur",
    "Abbottabad",
    "Mardan",
    "Mingora",
    "Gujrat",
    "Jhelum",
    "Rahim Yar Khan",
    "Sahiwal",
    "Okara",
    "Wah Cantt",
    "Taxila",
    "Dera Ghazi Khan",
    "Muzaffarabad",
    "Gilgit",
    "Skardu",
    "Nawabshah",
    "Larkana",
    "Chiniot",
    "Kasur",
    "Sheikhupura",
    "Attock",
    "Nowshera",
    "Swabi",
    "Mansehra",
    "Kohat",
    "Bannu",
    "Dera Ismail Khan"

];


/* =====================================================
   ELEMENTS
===================================================== */

const authScreen =
    document.getElementById("authScreen");

const app =
    document.getElementById("app");

const loginForm =
    document.getElementById("loginForm");

const signupForm =
    document.getElementById("signupForm");

const showSignup =
    document.getElementById("showSignup");

const showLogin =
    document.getElementById("showLogin");

const loginFormElement =
    document.getElementById("loginFormElement");

const signupFormElement =
    document.getElementById("signupFormElement");

const signupCity =
    document.getElementById("signupCity");

const reportCity =
    document.getElementById("reportCity");

const sidebar =
    document.getElementById("sidebar");

const mobileMenu =
    document.getElementById("mobileMenu");

const sidebarOverlay =
    document.getElementById("sidebarOverlay");

const logoutBtn =
    document.getElementById("logoutBtn");

const userName =
    document.getElementById("userName");

const userRole =
    document.getElementById("userRole");

const userAvatar =
    document.getElementById("userAvatar");

const topAvatar =
    document.getElementById("topAvatar");

const currentCity =
    document.getElementById("currentCity");

const heroCity =
    document.getElementById("heroCity");

const cityStat =
    document.getElementById("cityStat");

const mapCityLabel =
    document.getElementById("mapCityLabel");

const toast =
    document.getElementById("toast");

const toastTitle =
    document.getElementById("toastTitle");

const toastMessage =
    document.getElementById("toastMessage");


/* =====================================================
   STATE
===================================================== */

let currentUser = null;

let currentLanguage = "en";

let cameraStream = null;

let capturedPhoto = null;

let currentCoordinates = {
    latitude: null,
    longitude: null
};


/* =====================================================
   TRANSLATIONS
===================================================== */

const translations = {

    en: {

        /* ---------- GENERAL ---------- */

        dashboard: "Dashboard",
        reportIssue: "Report Issue",
        myReports: "My Reports",
        map: "Issue Map",
        language: "Language",
        citizenPortal: "CITIZEN PORTAL",
        government: "Government",
        administration: "Administration",
        pakistanCivicAI: "Pakistan Civic AI",
        pakistan: "Pakistan",
        city: "City",
        yourCity: "Your City",
        location: "Location",
        status: "Status",
        date: "Date",
        issue: "Issue",
        high: "High",
        medium: "Medium",
        low: "Low",
        resolved: "Resolved",
        reviewing: "Reviewing",
        inProgress: "In Progress",
        submitted: "Submitted",
        required: "REQUIRED",
        secure: "SECURE",
        protected: "PROTECTED",

        /* ---------- AUTH ---------- */

        builtForPakistan: "🇵🇰 BUILT FOR PAKISTAN",
        makeCityBetter: "Make your city",
        better: "better.",
        authDescription:
            "Report civic problems, locate them on the map, and let AI help connect communities with responsible authorities.",
        cameraBasedReporting: "Camera-based reporting",
        cameraBasedReportingDesc:
            "Capture real civic issues directly.",
        locationAware: "Location aware",
        locationAwareDesc:
            "Pin problems accurately on the map.",
        aiPowered: "AI powered",
        aiPoweredDesc:
            "Analyze and prioritize civic issues.",
        authFooter:
            "CivicLens • AI-powered civic management",

        welcomeBack: "Welcome back",
        signInSubtitle:
            "Sign in to your CivicLens account.",
        email: "Email",
        password: "Password",
        emailPlaceholder: "you@example.com",
        passwordPlaceholder: "Enter your password",
        rememberMe: "Remember me",
        forgotPassword: "Forgot password?",
        signIn: "Sign In",
        or: "or",
        tryDemoMode: "Try Demo Mode",
        dontHaveAccount: "Don't have an account?",
        createAccount: "Create account",
        signupSubtitle:
            "Join CivicLens and help improve your city.",
        fullName: "Full Name",
        fullNamePlaceholder: "Your full name",
        createPasswordPlaceholder:
            "Create a password",
        selectYourCity: "Select your city",
        alreadyHaveAccount:
            "Already have an account?",

        /* ---------- DASHBOARD ---------- */

        civicLensAIOnline: "CIVICLENS AI ONLINE",
        letsImprove: "Let's improve",
        dashboardHeroDescription:
            "Report civic problems and help your community get them resolved faster.",
        reportAnIssue: "Report an Issue",
        totalReports: "Total Reports",
        thisMonth4: "+4 this month",
        beingHandled: "Being handled",
        resolutionRate: "58% resolution rate",
        quickAction: "QUICK ACTION",
        reportCivicIssue: "Report a civic issue",
        quickReportDescription:
            "See a pothole, broken streetlight, overflowing drain or waste problem? Capture it directly using your camera.",
        capture: "Capture",
        locate: "Locate",
        analyze: "Analyze",
        submit: "Submit",
        startReport: "Start Report",
        recentActivity: "RECENT ACTIVITY",
        yourReports: "Your reports",
        viewAll: "View all",
        largePothole: "Large pothole",
        twoHoursAgo: "2 hours ago",
        brokenStreetlight: "Broken streetlight",
        yesterday: "Yesterday",
        wasteCollection: "Waste collection",
        threeDaysAgo: "3 days ago",
        reportsProtected: "Your reports are protected",
        reportsProtectedDescription:
            "CivicLens uses authenticated accounts, protected API access and role-based permissions for citizens, government users and administrators.",

        /* ---------- REPORT PAGE ---------- */

        civicReporting: "CIVIC REPORTING",
        reportIntro:
            "Capture the problem, confirm its location, and let CivicLens AI analyze it.",
        secureReport: "Secure Report",
        step1: "STEP 1",
        takePhoto: "Take a Photo",
        cameraDescription:
            "CivicLens only accepts photos captured directly through your camera. Gallery and file uploads are disabled.",
        cameraReady: "Camera ready",
        cameraPermission:
            "Your browser will ask for camera permission.",
        startCamera: "Start Camera",
        capturePhoto: "Capture Photo",
        retake: "Retake",
        cameraSecurity:
            "Photos are captured from your device camera only.",
        step2: "STEP 2",
        selectCity: "Select city",
        useCurrentLocation:
            "Use My Current Location",
        locationPreview: "Location preview",
        latitude: "Latitude",
        longitude: "Longitude",
        notDetected: "Not detected",
        step3: "STEP 3",
        describeProblem: "Describe the Problem",
        aiAnalysis: "AI ANALYSIS",
        description: "Description",
        descriptionPlaceholder:
            "Describe what you observed. For example: A large pothole is blocking half of the road near the intersection...",
        clear: "Clear",
        analyzeWithAI: "Analyze with AI",
        aiAnalysisComplete: "AI ANALYSIS COMPLETE",
        issueDetected: "Issue detected",
        issueType: "Issue Type",
        severity: "Severity",
        priority: "Priority",
        urgent: "Urgent",
        normal: "Normal",
        defaultAIMessage:
            "The issue appears to require attention from the relevant municipal department.",
        submitReport: "Submit Report",

        /* ---------- MY REPORTS ---------- */

        citizenActivity: "CITIZEN ACTIVITY",
        trackReports:
            "Track the civic issues you have reported.",
        newReport: "New Report",
        searchReports: "Search your reports...",
        allStatus: "All Status",

        /* ---------- MAP ---------- */

        civicIntelligence: "CIVIC INTELLIGENCE",
        issueMap: "Issue Map",
        mapDescription:
            "Explore reported civic problems around your selected city.",
        highPriorityPothole: "High priority pothole",
        streetlight: "Streetlight",
        resolvedIssue: "Resolved issue",
        drainageIssue: "Drainage issue",
        civicIssueOverview: "Civic issue overview",

        /* ---------- GOVERNMENT ---------- */

        governmentPortal: "GOVERNMENT PORTAL",
        civicOperations: "Civic Operations",
        governmentDescription:
            "Review, prioritize and manage civic reports submitted by citizens.",
        pendingReports: "Pending Reports",
        highPriority: "High Priority",
        projectsActive: "Projects Active",
        priorityQueue: "PRIORITY QUEUE",
        reportsRequiringAttention:
            "Reports requiring attention",
        export: "Export",
        majorRoadDamage: "Major road damage",
        aiSeverityHigh: "AI severity: HIGH",
        drainageBlockage: "Drainage blockage",
        aiSeverityMedium: "AI severity: MEDIUM",
        floodingRisk: "Flooding risk",
        review: "Review",

        /* ---------- ADMIN ---------- */

        systemAdministration: "SYSTEM ADMINISTRATION",
        administrator: "Administrator",
        adminDescription:
            "Manage users, permissions and CivicLens system security.",
        securityControlsActive:
            "Security controls active",
        securityControlsDescription:
            "Authentication, JWT-based API access and role-based authorization are configured for protected operations.",
        users: "Users",
        registeredUsers: "2,847 registered users",
        manageUsers: "Manage Users",
        rolesPermissions: "Roles & Permissions",
        roleTypes: "Citizen • Government • Admin",
        manageRoles: "Manage Roles",
        cities: "Cities",
        pakistaniCitiesSupported:
            "Pakistani cities supported",
        manageCities: "Manage Cities",
        systemData: "System Data",
        reportsProjectsDecisions:
            "Reports, projects and decisions",
        viewSystemData: "View System Data",

        /* ---------- UI ---------- */

        notifications: "Notifications",
        openMenu: "Open menu",
        logout: "Logout",

        /* ---------- TOASTS ---------- */

        success: "Success",
        actionCompleted: "Action completed.",
        missingInformation: "Missing information",
        completeAllFields:
            "Please complete all fields.",
        accountCreated: "Account created",
        welcomeToCivicLens:
            "Welcome to CivicLens.",
        loginSuccessful: "Login successful",
        welcomeBackToCivicLens:
            "Welcome back to CivicLens.",
        demoMode: "Demo Mode",
        demoAccountActivated:
            "CivicLens demo account activated.",
        loggedOut: "Logged out",
        signedOut: "You have been signed out.",
        languageChanged: "Language changed",
        englishActive: "English is now active.",
        cameraUnavailable: "Camera unavailable",
        cameraUnsupported:
            "Your browser does not support camera access.",
        cameraReadyToast: "Camera ready",
        pointCamera:
            "Point the camera at the civic issue.",
        cameraPermissionRequired:
            "Camera permission required",
        allowCamera:
            "Please allow camera access in your browser.",
        cameraNotActive: "Camera not active",
        startCameraFirst:
            "Start the camera first.",
        cameraLoading: "Camera loading",
        waitForCamera:
            "Please wait for the camera.",
        photoCaptured: "Photo captured",
        photoReady:
            "Your civic issue photo is ready.",
        locationUnavailable: "Location unavailable",
        locationUnsupported:
            "Your browser does not support location.",
        detectingLocation: "Detecting Location...",
        locationDetected: "Location detected",
        currentLocationCaptured:
            "Your current location has been captured.",
        locationPermissionRequired:
            "Location permission required",
        allowLocation:
            "Please allow location access.",
        photoRequired: "Photo required",
        takePhotoBeforeAnalysis:
            "Take a photo before analyzing the issue.",
        cityRequired: "City required",
        selectCityToast:
            "Please select your city.",
        descriptionRequired: "Description required",
        describeIssueFirst:
            "Describe the civic issue first.",
        analyzing: "Analyzing...",
        aiAnalysisCompleteToast:
            "AI analysis complete",
        issueAnalyzed:
            "The issue has been analyzed successfully.",
        aiError: "AI error",
        unableToAnalyze:
            "Unable to analyze the issue.",
        photoMissing: "Photo missing",
        capturePhotoFirst:
            "Capture an issue photo first.",
        incompleteReport: "Incomplete report",
        completeReport:
            "Please complete the report.",
        submitting: "Submitting...",
        reportSubmitted: "Report submitted",
        reportSubmittedSuccessfully:
            "Your civic report has been submitted successfully.",
        notificationsTitle: "Notifications",
        newUpdates:
            "You have 3 new CivicLens updates.",

        /* ---------- AI RESULT TYPES ---------- */

        potholeRoadDamage: "Pothole / Road Damage",
        streetlightIssue: "Streetlight",
        drainageFlooding: "Drainage / Flooding",
        wasteManagement: "Waste Management",
        civicIssue: "Civic Issue",
        highSeverity: "High",
        mediumSeverity: "Medium",
        lowSeverity: "Low",
        urgentPriority: "Urgent",
        normalPriority: "Normal",
        lowPriority: "Low",

        aiRecommendation:
            "CivicLens AI has analyzed the submitted issue and recommends that the relevant municipal department review it."
    },


    ur: {

        /* ---------- GENERAL ---------- */

        dashboard: "ڈیش بورڈ",
        reportIssue: "مسئلہ رپورٹ کریں",
        myReports: "میری رپورٹس",
        map: "مسائل کا نقشہ",
        language: "زبان",
        citizenPortal: "شہری پورٹل",
        government: "حکومت",
        administration: "انتظامیہ",
        pakistanCivicAI: "پاکستان سِوک AI",
        pakistan: "پاکستان",
        city: "شہر",
        yourCity: "آپ کا شہر",
        location: "مقام",
        status: "حیثیت",
        date: "تاریخ",
        issue: "مسئلہ",
        high: "زیادہ",
        medium: "درمیانہ",
        low: "کم",
        resolved: "حل شدہ",
        reviewing: "جائزہ جاری ہے",
        inProgress: "زیرِ کارروائی",
        submitted: "جمع شدہ",
        required: "ضروری",
        secure: "محفوظ",
        protected: "محفوظ شدہ",

        /* ---------- AUTH ---------- */

        builtForPakistan: "🇵🇰 پاکستان کے لیے بنایا گیا",
        makeCityBetter: "اپنے شہر کو",
        better: "بہتر بنائیں۔",
        authDescription:
            "شہری مسائل کی رپورٹ کریں، انہیں نقشے پر دیکھیں اور AI کی مدد سے متعلقہ ذمہ دار اداروں تک پہنچائیں۔",
        cameraBasedReporting: "کیمرے کے ذریعے رپورٹنگ",
        cameraBasedReportingDesc:
            "حقیقی شہری مسائل کی براہِ راست تصویر لیں۔",
        locationAware: "مقام کی نشاندہی",
        locationAwareDesc:
            "مسائل کو نقشے پر درست مقام کے ساتھ نشان زد کریں۔",
        aiPowered: "AI سے چلنے والا نظام",
        aiPoweredDesc:
            "شہری مسائل کا تجزیہ اور ترجیح بندی کریں۔",
        authFooter:
            "CivicLens • AI پر مبنی شہری انتظام",

        welcomeBack: "خوش آمدید",
        signInSubtitle:
            "اپنے CivicLens اکاؤنٹ میں سائن اِن کریں۔",
        email: "ای میل",
        password: "پاس ورڈ",
        emailPlaceholder: "you@example.com",
        passwordPlaceholder: "اپنا پاس ورڈ درج کریں",
        rememberMe: "مجھے یاد رکھیں",
        forgotPassword: "پاس ورڈ بھول گئے؟",
        signIn: "سائن اِن",
        or: "یا",
        tryDemoMode: "ڈیمو موڈ آزمائیں",
        dontHaveAccount: "اکاؤنٹ موجود نہیں؟",
        createAccount: "اکاؤنٹ بنائیں",
        signupSubtitle:
            "CivicLens میں شامل ہوں اور اپنے شہر کو بہتر بنانے میں مدد کریں۔",
        fullName: "پورا نام",
        fullNamePlaceholder: "اپنا پورا نام درج کریں",
        createPasswordPlaceholder:
            "پاس ورڈ بنائیں",
        selectYourCity: "اپنا شہر منتخب کریں",
        alreadyHaveAccount:
            "پہلے سے اکاؤنٹ موجود ہے؟",

        /* ---------- DASHBOARD ---------- */

        civicLensAIOnline: "CIVICLENS AI آن لائن",
        letsImprove: "آئیں بہتر بنائیں",
        dashboardHeroDescription:
            "شہری مسائل کی رپورٹ کریں اور اپنی کمیونٹی میں انہیں تیزی سے حل کروانے میں مدد کریں۔",
        reportAnIssue: "مسئلہ رپورٹ کریں",
        totalReports: "کل رپورٹس",
        thisMonth4: "اس ماہ +4",
        beingHandled: "کارروائی جاری ہے",
        resolutionRate: "حل ہونے کی شرح 58٪",
        quickAction: "فوری کارروائی",
        reportCivicIssue: "شہری مسئلہ رپورٹ کریں",
        quickReportDescription:
            "کیا آپ کو گڑھا، خراب اسٹریٹ لائٹ، بھرا ہوا نالہ یا کچرے کا مسئلہ نظر آیا؟ کیمرے سے براہِ راست تصویر لیں۔",
        capture: "تصویر لیں",
        locate: "مقام معلوم کریں",
        analyze: "تجزیہ کریں",
        submit: "جمع کریں",
        startReport: "رپورٹ شروع کریں",
        recentActivity: "حالیہ سرگرمی",
        yourReports: "آپ کی رپورٹس",
        viewAll: "سب دیکھیں",
        largePothole: "بڑا سڑک کا گڑھا",
        twoHoursAgo: "2 گھنٹے پہلے",
        brokenStreetlight: "خراب اسٹریٹ لائٹ",
        yesterday: "کل",
        wasteCollection: "کچرا جمع کرنا",
        threeDaysAgo: "3 دن پہلے",
        reportsProtected: "آپ کی رپورٹس محفوظ ہیں",
        reportsProtectedDescription:
            "CivicLens شہریوں، حکومتی صارفین اور منتظمین کے لیے تصدیق شدہ اکاؤنٹس، محفوظ API رسائی اور کردار پر مبنی اجازتیں استعمال کرتا ہے۔",

        /* ---------- REPORT PAGE ---------- */

        civicReporting: "شہری رپورٹنگ",
        reportIntro:
            "مسئلے کی تصویر لیں، مقام کی تصدیق کریں اور CivicLens AI سے اس کا تجزیہ کروائیں۔",
        secureReport: "محفوظ رپورٹ",
        step1: "مرحلہ 1",
        takePhoto: "تصویر لیں",
        cameraDescription:
            "CivicLens صرف کیمرے کے ذریعے براہِ راست لی گئی تصاویر قبول کرتا ہے۔ گیلری اور فائل اپ لوڈ بند ہیں۔",
        cameraReady: "کیمرہ تیار ہے",
        cameraPermission:
            "آپ کا براؤزر کیمرے کی اجازت طلب کرے گا۔",
        startCamera: "کیمرہ شروع کریں",
        capturePhoto: "تصویر لیں",
        retake: "دوبارہ لیں",
        cameraSecurity:
            "تصاویر صرف آپ کے ڈیوائس کے کیمرے سے لی جاتی ہیں۔",
        step2: "مرحلہ 2",
        selectCity: "شہر منتخب کریں",
        useCurrentLocation:
            "میرا موجودہ مقام استعمال کریں",
        locationPreview: "مقام کا پیش منظر",
        latitude: "عرض بلد",
        longitude: "طول بلد",
        notDetected: "معلوم نہیں ہوا",
        step3: "مرحلہ 3",
        describeProblem: "مسئلہ بیان کریں",
        aiAnalysis: "AI تجزیہ",
        description: "تفصیل",
        descriptionPlaceholder:
            "جو کچھ آپ نے دیکھا اسے بیان کریں۔ مثال کے طور پر: چوراہے کے قریب سڑک کا ایک بڑا گڑھا آدھی سڑک کو روک رہا ہے...",
        clear: "صاف کریں",
        analyzeWithAI: "AI سے تجزیہ کریں",
        aiAnalysisComplete: "AI تجزیہ مکمل",
        issueDetected: "مسئلہ معلوم ہوا",
        issueType: "مسئلے کی قسم",
        severity: "شدت",
        priority: "ترجیح",
        urgent: "فوری",
        normal: "معمول",
        defaultAIMessage:
            "یہ مسئلہ متعلقہ میونسپل محکمے کی توجہ کا متقاضی معلوم ہوتا ہے۔",
        submitReport: "رپورٹ جمع کریں",

        /* ---------- MY REPORTS ---------- */

        citizenActivity: "شہری سرگرمی",
        trackReports:
            "ان شہری مسائل کی نگرانی کریں جن کی آپ نے رپورٹ کی ہے۔",
        newReport: "نئی رپورٹ",
        searchReports: "اپنی رپورٹس تلاش کریں...",
        allStatus: "تمام حیثیتیں",

        /* ---------- MAP ---------- */

        civicIntelligence: "شہری ذہانت",
        issueMap: "مسائل کا نقشہ",
        mapDescription:
            "اپنے منتخب شہر کے اردگرد رپورٹ کیے گئے شہری مسائل دیکھیں۔",
        highPriorityPothole:
            "زیادہ ترجیح والا سڑک کا گڑھا",
        streetlight: "اسٹریٹ لائٹ",
        resolvedIssue: "حل شدہ مسئلہ",
        drainageIssue: "نکاسی آب کا مسئلہ",
        civicIssueOverview: "شہری مسائل کا جائزہ",

        /* ---------- GOVERNMENT ---------- */

        governmentPortal: "حکومتی پورٹل",
        civicOperations: "شہری کارروائیاں",
        governmentDescription:
            "شہریوں کی جانب سے جمع کرائی گئی رپورٹس کا جائزہ لیں، ترجیح مقرر کریں اور ان کا انتظام کریں۔",
        pendingReports: "زیر التوا رپورٹس",
        highPriority: "زیادہ ترجیح",
        projectsActive: "فعال منصوبے",
        priorityQueue: "ترجیحی فہرست",
        reportsRequiringAttention:
            "توجہ کی ضرورت والی رپورٹس",
        export: "برآمد کریں",
        majorRoadDamage: "سڑک کو بڑا نقصان",
        aiSeverityHigh: "AI شدت: زیادہ",
        drainageBlockage: "نکاسی آب میں رکاوٹ",
        aiSeverityMedium: "AI شدت: درمیانی",
        floodingRisk: "سیلاب کا خطرہ",
        review: "جائزہ",

        /* ---------- ADMIN ---------- */

        systemAdministration: "سسٹم انتظامیہ",
        administrator: "منتظم",
        adminDescription:
            "صارفین، اجازتوں اور CivicLens سسٹم کی سیکیورٹی کا انتظام کریں۔",
        securityControlsActive:
            "سیکیورٹی کنٹرولز فعال ہیں",
        securityControlsDescription:
            "تصدیق، JWT پر مبنی API رسائی اور کردار پر مبنی اجازت محفوظ کارروائیوں کے لیے ترتیب دی گئی ہے۔",
        users: "صارفین",
        registeredUsers: "2,847 رجسٹرڈ صارفین",
        manageUsers: "صارفین کا انتظام",
        rolesPermissions: "کردار اور اجازتیں",
        roleTypes: "شہری • حکومت • منتظم",
        manageRoles: "کردار کا انتظام",
        cities: "شہر",
        pakistaniCitiesSupported:
            "پاکستانی شہروں کی معاونت",
        manageCities: "شہروں کا انتظام",
        systemData: "سسٹم ڈیٹا",
        reportsProjectsDecisions:
            "رپورٹس، منصوبے اور فیصلے",
        viewSystemData: "سسٹم ڈیٹا دیکھیں",

        /* ---------- UI ---------- */

        notifications: "اطلاعات",
        openMenu: "مینو کھولیں",
        logout: "لاگ آؤٹ",

        /* ---------- TOASTS ---------- */

        success: "کامیاب",
        actionCompleted: "کارروائی مکمل ہوگئی۔",
        missingInformation: "معلومات نامکمل ہیں",
        completeAllFields:
            "براہِ کرم تمام خانے مکمل کریں۔",
        accountCreated: "اکاؤنٹ بن گیا",
        welcomeToCivicLens:
            "CivicLens میں خوش آمدید۔",
        loginSuccessful: "لاگ اِن کامیاب",
        welcomeBackToCivicLens:
            "CivicLens میں دوبارہ خوش آمدید۔",
        demoMode: "ڈیمو موڈ",
        demoAccountActivated:
            "CivicLens ڈیمو اکاؤنٹ فعال ہوگیا۔",
        loggedOut: "لاگ آؤٹ ہوگیا",
        signedOut:
            "آپ سائن آؤٹ ہوگئے ہیں۔",
        languageChanged: "زبان تبدیل ہوگئی",
        englishActive:
            "انگریزی فعال ہوگئی ہے۔",
        cameraUnavailable: "کیمرہ دستیاب نہیں",
        cameraUnsupported:
            "آپ کا براؤزر کیمرے تک رسائی کی معاونت نہیں کرتا۔",
        cameraReadyToast: "کیمرہ تیار ہے",
        pointCamera:
            "کیمرے کو شہری مسئلے کی طرف کریں۔",
        cameraPermissionRequired:
            "کیمرے کی اجازت درکار ہے",
        allowCamera:
            "براہِ کرم اپنے براؤزر میں کیمرے کی اجازت دیں۔",
        cameraNotActive: "کیمرہ فعال نہیں",
        startCameraFirst:
            "پہلے کیمرہ شروع کریں۔",
        cameraLoading: "کیمرہ لوڈ ہورہا ہے",
        waitForCamera:
            "براہِ کرم کیمرے کے لیے انتظار کریں۔",
        photoCaptured: "تصویر لے لی گئی",
        photoReady:
            "آپ کے شہری مسئلے کی تصویر تیار ہے۔",
        locationUnavailable:
            "مقام دستیاب نہیں",
        locationUnsupported:
            "آپ کا براؤزر مقام کی سہولت فراہم نہیں کرتا۔",
        detectingLocation: "مقام معلوم کیا جارہا ہے...",
        locationDetected: "مقام معلوم ہوگیا",
        currentLocationCaptured:
            "آپ کا موجودہ مقام محفوظ ہوگیا ہے۔",
        locationPermissionRequired:
            "مقام کی اجازت درکار ہے",
        allowLocation:
            "براہِ کرم مقام تک رسائی کی اجازت دیں۔",
        photoRequired: "تصویر ضروری ہے",
        takePhotoBeforeAnalysis:
            "مسئلے کا تجزیہ کرنے سے پہلے تصویر لیں۔",
        cityRequired: "شہر ضروری ہے",
        selectCityToast:
            "براہِ کرم اپنا شہر منتخب کریں۔",
        descriptionRequired: "تفصیل ضروری ہے",
        describeIssueFirst:
            "پہلے شہری مسئلہ بیان کریں۔",
        analyzing: "تجزیہ کیا جارہا ہے...",
        aiAnalysisCompleteToast:
            "AI تجزیہ مکمل ہوگیا",
        issueAnalyzed:
            "مسئلے کا کامیابی سے تجزیہ ہوگیا۔",
        aiError: "AI خرابی",
        unableToAnalyze:
            "مسئلے کا تجزیہ نہیں ہوسکا۔",
        photoMissing: "تصویر موجود نہیں",
        capturePhotoFirst:
            "پہلے مسئلے کی تصویر لیں۔",
        incompleteReport: "رپورٹ نامکمل ہے",
        completeReport:
            "براہِ کرم رپورٹ مکمل کریں۔",
        submitting: "جمع کیا جارہا ہے...",
        reportSubmitted: "رپورٹ جمع ہوگئی",
        reportSubmittedSuccessfully:
            "آپ کی شہری رپورٹ کامیابی سے جمع ہوگئی ہے۔",
        notificationsTitle: "اطلاعات",
        newUpdates:
            "CivicLens کی 3 نئی اپ ڈیٹس موجود ہیں۔",

        /* ---------- AI RESULT TYPES ---------- */

        potholeRoadDamage:
            "سڑک کا گڑھا / سڑک کو نقصان",
        streetlightIssue: "اسٹریٹ لائٹ",
        drainageFlooding:
            "نکاسی آب / سیلاب",
        wasteManagement: "کچرے کا انتظام",
        civicIssue: "شہری مسئلہ",
        highSeverity: "زیادہ",
        mediumSeverity: "درمیانہ",
        lowSeverity: "کم",
        urgentPriority: "فوری",
        normalPriority: "معمول",
        lowPriority: "کم",

        aiRecommendation:
            "CivicLens AI نے جمع کرائے گئے مسئلے کا تجزیہ کیا ہے اور متعلقہ میونسپل محکمے کو اس کا جائزہ لینے کی سفارش کی ہے۔"
    }

};


/* =====================================================
   TRANSLATION HELPERS
===================================================== */

function t(key) {

    return (
        translations[currentLanguage] &&
        translations[currentLanguage][key]
    ) ||
    translations.en[key] ||
    key;

}


function applyTranslations() {

    /* ---------- TEXT ---------- */

    document
        .querySelectorAll("[data-i18n]")
        .forEach(element => {

            const key =
                element.dataset.i18n;

            const translated =
                t(key);

            if (translated !== key) {

                element.textContent =
                    translated;

            }

        });


    /* ---------- PLACEHOLDERS ---------- */

    document
        .querySelectorAll("[data-i18n-placeholder]")
        .forEach(element => {

            const key =
                element.dataset.i18nPlaceholder;

            element.placeholder =
                t(key);

        });


    /* ---------- TITLES ---------- */

    document
        .querySelectorAll("[data-i18n-title]")
        .forEach(element => {

            const key =
                element.dataset.i18nTitle;

            element.title =
                t(key);

            element.setAttribute(
                "aria-label",
                t(key)
            );

        });


    /* ---------- ROLE ---------- */

    if (currentUser) {

        userRole.textContent =
            formatRole(
                currentUser.role
            );

    }

}


/* =====================================================
   CITY DROPDOWNS
===================================================== */

function populateCities() {

    pakistanCities.forEach(city => {

        const signupOption =
            document.createElement("option");

        signupOption.value = city;

        signupOption.textContent = city;

        signupCity.appendChild(
            signupOption
        );


        const reportOption =
            document.createElement("option");

        reportOption.value = city;

        reportOption.textContent = city;

        reportCity.appendChild(
            reportOption
        );

    });

}


populateCities();


/* =====================================================
   AUTH SCREEN
===================================================== */

showSignup.addEventListener("click", () => {

    loginForm.classList.remove("active");

    signupForm.classList.add("active");

});


showLogin.addEventListener("click", () => {

    signupForm.classList.remove("active");

    loginForm.classList.add("active");

});


/* =====================================================
   PASSWORD TOGGLE
===================================================== */

document
    .querySelectorAll(".password-toggle")
    .forEach(button => {

        button.addEventListener("click", () => {

            const targetId =
                button.dataset.target;

            const input =
                document.getElementById(
                    targetId
                );

            const icon =
                button.querySelector("i");


            if (input.type === "password") {

                input.type = "text";

                icon.classList.remove(
                    "fa-eye"
                );

                icon.classList.add(
                    "fa-eye-slash"
                );

            }

            else {

                input.type = "password";

                icon.classList.remove(
                    "fa-eye-slash"
                );

                icon.classList.add(
                    "fa-eye"
                );

            }

        });

    });


/* =====================================================
   SIGNUP
===================================================== */

signupFormElement.addEventListener(
    "submit",
    async event => {

        event.preventDefault();


        const name =
            document
                .getElementById("signupName")
                .value
                .trim();


        const email =
            document
                .getElementById("signupEmail")
                .value
                .trim();


        const password =
            document
                .getElementById("signupPassword")
                .value;


        const city =
            signupCity.value;


        if (!name || !email || !password || !city) {

            showToast(
                t("missingInformation"),
                t("completeAllFields")
            );

            return;

        }


        /*
            TEMPORARY FRONTEND DEMO

            Later replace this with:

            fetch(`${API_BASE_URL}/auth/signup`, ...)

            Your backend will hash the password
            and create the user.
        */


        const demoUser = {

            user_id:
                "CIT-" +
                Date.now(),

            name: name,

            email: email,

            role: "citizen",

            city: city

        };


        /*
            Do NOT store passwords in localStorage.
        */


        localStorage.setItem(
            "civic_user",
            JSON.stringify(demoUser)
        );


        showToast(
            t("accountCreated"),
            t("welcomeToCivicLens")
        );


        setTimeout(() => {

            startApplication(
                demoUser
            );

        }, 700);

    }
);


/* =====================================================
   LOGIN
===================================================== */

loginFormElement.addEventListener(
    "submit",
    async event => {

        event.preventDefault();


        const email =
            document
                .getElementById("loginEmail")
                .value
                .trim();


        const password =
            document
                .getElementById("loginPassword")
                .value;


        if (!email || !password) {

            showToast(
                t("missingInformation"),
                t("completeAllFields")
            );

            return;

        }


        /*
            TEMPORARY DEMO LOGIN.

            Later this becomes:

            POST /auth/login
        */


        const demoUser = {

            user_id: "CIT-001",

            name: "Hamza Khan",

            email: email,

            role: "citizen",

            city: "Rawalpindi"

        };


        localStorage.setItem(
            "civic_user",
            JSON.stringify(demoUser)
        );


        showToast(
            t("loginSuccessful"),
            t("welcomeBackToCivicLens")
        );


        setTimeout(() => {

            startApplication(
                demoUser
            );

        }, 600);

    }
);


/* =====================================================
   DEMO LOGIN
===================================================== */

const demoLogin =
    document.getElementById(
        "demoLogin"
    );


demoLogin.addEventListener(
    "click",
    () => {

        const demoUser = {

            user_id: "CIT-DEMO",

            name: "Hamza Khan",

            email: "demo@civiclens.pk",

            role: "citizen",

            city: "Rawalpindi"

        };


        localStorage.setItem(
            "civic_user",
            JSON.stringify(demoUser)
        );


        startApplication(
            demoUser
        );


        showToast(
            t("demoMode"),
            t("demoAccountActivated")
        );

    }
);


/* =====================================================
   START APPLICATION
===================================================== */

function startApplication(user) {

    currentUser = user;


    authScreen.classList.add(
        "hidden"
    );

    app.classList.remove(
        "hidden"
    );


    updateUserInterface();

    applyTranslations();

    showPage("dashboard");

}


/* =====================================================
   USER INTERFACE
===================================================== */

function updateUserInterface() {

    if (!currentUser) {
        return;
    }


    const name =
        currentUser.name ||
        "CivicLens User";


    const role =
        currentUser.role ||
        "citizen";


    const city =
        currentUser.city ||
        "Rawalpindi";


    userName.textContent =
        name;


    userRole.textContent =
        formatRole(role);


    const initials =
        getInitials(name);


    userAvatar.textContent =
        initials;


    topAvatar.textContent =
        initials;


    currentCity.textContent =
        city;


    heroCity.textContent =
        city;


    cityStat.textContent =
        city;


    mapCityLabel.textContent =
        city;


    reportCity.value =
        city;


    setupRoleVisibility(
        role
    );

}


/* =====================================================
   FORMAT ROLE
===================================================== */

function formatRole(role) {

    if (role === "government") {

        return t("government");

    }


    if (role === "admin") {

        return t("administrator");

    }


    return currentLanguage === "ur"
        ? "شہری"
        : "Citizen";

}


/* =====================================================
   INITIALS
===================================================== */

function getInitials(name) {

    return name
        .split(" ")
        .map(part => part[0])
        .slice(0, 2)
        .join("")
        .toUpperCase();

}


/* =====================================================
   ROLE VISIBILITY
===================================================== */

function setupRoleVisibility(role) {

    document
        .querySelectorAll(".citizen-only")
        .forEach(element => {

            element.style.display =
                role === "citizen"
                    ? ""
                    : "none";

        });


    document
        .querySelectorAll(".government-only")
        .forEach(element => {

            element.style.display =
                role === "government"
                    ? ""
                    : "none";

        });


    document
        .querySelectorAll(".admin-only")
        .forEach(element => {

            element.style.display =
                role === "admin"
                    ? ""
                    : "none";

        });

}


/* =====================================================
   PAGE NAVIGATION
===================================================== */

const navItems =
    document.querySelectorAll(
        ".nav-item"
    );


navItems.forEach(item => {

    item.addEventListener(
        "click",
        () => {

            const page =
                item.dataset.page;


            showPage(page);


            closeSidebar();

        }
    );

});


document
    .querySelectorAll("[data-page-link]")
    .forEach(button => {

        button.addEventListener(
            "click",
            () => {

                const page =
                    button.dataset.pageLink;


                showPage(page);

            }
        );

    });


function showPage(pageName) {

    const pages =
        document.querySelectorAll(
            ".page"
        );


    pages.forEach(page => {

        page.classList.remove(
            "active-page"
        );

    });


    const targetPage =
        document.getElementById(
            `${pageName}Page`
        );


    if (!targetPage) {
        return;
    }


    targetPage.classList.add(
        "active-page"
    );


    navItems.forEach(item => {

        item.classList.remove(
            "active"
        );


        if (
            item.dataset.page ===
            pageName
        ) {

            item.classList.add(
                "active"
            );

        }

    });


    updatePageTitle(
        pageName
    );

}


/* =====================================================
   PAGE TITLE
===================================================== */

function updatePageTitle(page) {

    const title =
        document.getElementById(
            "pageTitle"
        );


    const eyebrow =
        document.getElementById(
            "pageEyebrow"
        );


    const titles = {

        dashboard: "dashboard",

        report: "reportAnIssue",

        myReports: "myReports",

        map: "issueMap",

        government: "civicOperations",

        admin: "administration"

    };


    const eyebrowKeys = {

        dashboard: "citizenPortal",

        report: "citizenPortal",

        myReports: "citizenActivity",

        map: "civicIntelligence",

        government: "governmentPortal",

        admin: "systemAdministration"

    };


    title.textContent =
        t(
            titles[page] ||
            "dashboard"
        );


    eyebrow.textContent =
        t(
            eyebrowKeys[page] ||
            "citizenPortal"
        );

}


/* =====================================================
   MOBILE SIDEBAR
===================================================== */

mobileMenu.addEventListener(
    "click",
    () => {

        sidebar.classList.add(
            "open"
        );

        sidebarOverlay.classList.add(
            "show"
        );

    }
);


sidebarOverlay.addEventListener(
    "click",
    closeSidebar
);


function closeSidebar() {

    sidebar.classList.remove(
        "open"
    );

    sidebarOverlay.classList.remove(
        "show"
    );

}


/* =====================================================
   LOGOUT
===================================================== */

logoutBtn.addEventListener(
    "click",
    () => {

        stopCamera();


        localStorage.removeItem(
            "civic_user"
        );


        currentUser = null;


        app.classList.add(
            "hidden"
        );

        authScreen.classList.remove(
            "hidden"
        );


        loginForm.classList.add(
            "active"
        );

        signupForm.classList.remove(
            "active"
        );


        showToast(
            t("loggedOut"),
            t("signedOut")
        );

    }
);


/* =====================================================
   LANGUAGE SWITCH
===================================================== */

document
    .querySelectorAll(".language-btn")
    .forEach(button => {

        button.addEventListener(
            "click",
            () => {

                const language =
                    button.dataset.language;


                changeLanguage(
                    language
                );

            }
        );

    });


function changeLanguage(language) {

    if (
        !translations[language]
    ) {

        return;

    }


    currentLanguage =
        language;


    document
        .querySelectorAll(".language-btn")
        .forEach(button => {

            button.classList.toggle(
                "active",
                button.dataset.language ===
                language
            );

        });


    /*
        Translate all static HTML
        text, placeholders and titles.
    */

    applyTranslations();


    /*
        Preserve the existing RTL
        system.
    */

    if (language === "ur") {

        document.body.classList.add(
            "rtl"
        );

        document.documentElement
            .setAttribute(
                "lang",
                "ur"
            );

        document.documentElement
            .setAttribute(
                "dir",
                "rtl"
            );

    }

    else {

        document.body.classList.remove(
            "rtl"
        );

        document.documentElement
            .setAttribute(
                "lang",
                "en"
            );

        document.documentElement
            .setAttribute(
                "dir",
                "ltr"
            );

    }


    /*
        Dynamic values need to be
        restored after translation.
    */

    if (currentUser) {

        updateUserInterface();

    }


    updatePageTitle(
        getCurrentPage()
    );


    showToast(
        t("languageChanged"),
        language === "ur"
            ? "اردو فعال ہوگئی ہے۔"
            : t("englishActive")
    );

}


/* =====================================================
   GET CURRENT PAGE
===================================================== */

function getCurrentPage() {

    const active =
        document.querySelector(
            ".page.active-page"
        );


    if (!active) {

        return "dashboard";

    }


    return active.id.replace(
        "Page",
        ""
    );

}


/* =====================================================
   CAMERA
===================================================== */

const startCamera =
    document.getElementById(
        "startCamera"
    );


const capturePhoto =
    document.getElementById(
        "capturePhoto"
    );


const retakePhoto =
    document.getElementById(
        "retakePhoto"
    );


const cameraVideo =
    document.getElementById(
        "cameraVideo"
    );


const cameraCanvas =
    document.getElementById(
        "cameraCanvas"
    );


const capturedImage =
    document.getElementById(
        "capturedImage"
    );


const cameraPlaceholder =
    document.getElementById(
        "cameraPlaceholder"
    );


const cameraFrame =
    document.getElementById(
        "cameraFrame"
    );


/*
    IMPORTANT:

    There is intentionally NO:

    <input type="file">

    and NO gallery upload.

    Camera access is through getUserMedia().
*/


startCamera.addEventListener(
    "click",
    async () => {

        try {

            if (
                !navigator.mediaDevices ||
                !navigator.mediaDevices.getUserMedia
            ) {

                showToast(
                    t("cameraUnavailable"),
                    t("cameraUnsupported")
                );

                return;

            }


            cameraStream =
                await navigator
                    .mediaDevices
                    .getUserMedia({

                        video: {

                            facingMode: {
                                ideal: "environment"
                            }

                        },

                        audio: false

                    });


            cameraVideo.srcObject =
                cameraStream;


            cameraVideo.style.display =
                "block";


            cameraPlaceholder.style.display =
                "none";


            capturedImage.style.display =
                "none";


            cameraFrame.style.display =
                "block";


            capturePhoto.disabled =
                false;


            retakePhoto.classList.add(
                "hidden"
            );


            startCamera.innerHTML = `
                <i class="fa-solid fa-camera"></i>
                <span data-i18n="cameraReady">Camera Active</span>
            `;


            /*
                We inserted a translation key
                dynamically, so translate it now.
            */

            applyTranslations();


            showToast(
                t("cameraReadyToast"),
                t("pointCamera")
            );

        }

        catch (error) {

            console.error(
                "Camera error:",
                error
            );


            showToast(
                t("cameraPermissionRequired"),
                t("allowCamera")
            );

        }

    }
);


/* =====================================================
   CAPTURE PHOTO
===================================================== */

capturePhoto.addEventListener(
    "click",
    () => {

        if (!cameraStream) {

            showToast(
                t("cameraNotActive"),
                t("startCameraFirst")
            );

            return;

        }


        const videoWidth =
            cameraVideo.videoWidth;


        const videoHeight =
            cameraVideo.videoHeight;


        if (
            !videoWidth ||
            !videoHeight
        ) {

            showToast(
                t("cameraLoading"),
                t("waitForCamera")
            );

            return;

        }


        cameraCanvas.width =
            videoWidth;


        cameraCanvas.height =
            videoHeight;


        const context =
            cameraCanvas.getContext(
                "2d"
            );


        context.drawImage(
            cameraVideo,
            0,
            0,
            videoWidth,
            videoHeight
        );


        capturedPhoto =
            cameraCanvas.toDataURL(
                "image/jpeg",
                .85
            );


        capturedImage.src =
            capturedPhoto;


        capturedImage.style.display =
            "block";


        cameraVideo.style.display =
            "none";


        cameraFrame.style.display =
            "none";


        capturePhoto.disabled =
            true;


        retakePhoto.classList.remove(
            "hidden"
        );


        stopCamera();


        showToast(
            t("photoCaptured"),
            t("photoReady")
        );

    }
);


/* =====================================================
   RETAKE PHOTO
===================================================== */

retakePhoto.addEventListener(
    "click",
    async () => {

        capturedPhoto = null;


        capturedImage.style.display =
            "none";


        retakePhoto.classList.add(
            "hidden"
        );


        await startCamera.click();

    }
);


/* =====================================================
   STOP CAMERA
===================================================== */

function stopCamera() {

    if (!cameraStream) {
        return;
    }


    cameraStream
        .getTracks()
        .forEach(track => {

            track.stop();

        });


    cameraStream = null;


    if (cameraVideo) {

        cameraVideo.srcObject = null;

    }

}


/* =====================================================
   LOCATION
===================================================== */

const getLocation =
    document.getElementById(
        "getLocation"
    );


const latitude =
    document.getElementById(
        "latitude"
    );


const longitude =
    document.getElementById(
        "longitude"
    );


const mapMarker =
    document.getElementById(
        "mapMarker"
    );


getLocation.addEventListener(
    "click",
    () => {

        if (!navigator.geolocation) {

            showToast(
                t("locationUnavailable"),
                t("locationUnsupported")
            );

            return;

        }


        getLocation.innerHTML = `
            <i class="fa-solid fa-spinner fa-spin"></i>
            <span data-i18n="detectingLocation">
                Detecting Location...
            </span>
        `;


        applyTranslations();


        navigator.geolocation.getCurrentPosition(

            position => {

                currentCoordinates.latitude =
                    position.coords.latitude;


                currentCoordinates.longitude =
                    position.coords.longitude;


                latitude.textContent =
                    currentCoordinates
                        .latitude
                        .toFixed(6);


                longitude.textContent =
                    currentCoordinates
                        .longitude
                        .toFixed(6);


                latitude.removeAttribute(
                    "data-i18n"
                );

                longitude.removeAttribute(
                    "data-i18n"
                );


                mapMarker.style.left =
                    "50%";


                mapMarker.style.top =
                    "50%";


                getLocation.innerHTML = `
                    <i class="fa-solid fa-location-dot"></i>
                    <span data-i18n="locationDetected">
                        Location Detected
                    </span>
                `;


                applyTranslations();


                showToast(
                    t("locationDetected"),
                    t("currentLocationCaptured")
                );

            },


            error => {

                console.error(
                    "Location error:",
                    error
                );


                getLocation.innerHTML = `
                    <i class="fa-solid fa-crosshairs"></i>
                    <span data-i18n="useCurrentLocation">
                        Use My Current Location
                    </span>
                `;


                applyTranslations();


                showToast(
                    t("locationPermissionRequired"),
                    t("allowLocation")
                );

            },


            {

                enableHighAccuracy: true,

                timeout: 10000,

                maximumAge: 0

            }

        );

    }
);


/* =====================================================
   DESCRIPTION COUNTER
===================================================== */

const issueDescription =
    document.getElementById(
        "issueDescription"
    );


const characterCount =
    document.getElementById(
        "characterCount"
    );


issueDescription.addEventListener(
    "input",
    () => {

        if (
            issueDescription.value.length >
            500
        ) {

            issueDescription.value =
                issueDescription.value.substring(
                    0,
                    500
                );

        }


        characterCount.textContent =
            issueDescription.value.length;

    }
);


/* =====================================================
   AI ANALYSIS
===================================================== */

const analyzeIssue =
    document.getElementById(
        "analyzeIssue"
    );


const aiResult =
    document.getElementById(
        "aiResult"
    );


analyzeIssue.addEventListener(
    "click",
    async () => {

        const description =
            issueDescription.value.trim();


        if (!capturedPhoto) {

            showToast(
                t("photoRequired"),
                t("takePhotoBeforeAnalysis")
            );

            return;

        }


        if (!reportCity.value) {

            showToast(
                t("cityRequired"),
                t("selectCityToast")
            );

            return;

        }


        if (!description) {

            showToast(
                t("descriptionRequired"),
                t("describeIssueFirst")
            );

            return;

        }


        const originalHTML =
            analyzeIssue.innerHTML;


        analyzeIssue.disabled =
            true;


        analyzeIssue.innerHTML = `
            <i class="fa-solid fa-spinner fa-spin"></i>
            <span data-i18n="analyzing">
                Analyzing...
            </span>
        `;


        applyTranslations();


        try {

            /*
                TEMPORARY DEMO DELAY
            */

            await delay(1600);


            const analysis = {

                issue_type:
                    detectIssueType(
                        description
                    ),

                severity:
                    detectSeverity(
                        description
                    ),

                priority:
                    detectPriority(
                        description
                    ),

                answer:
                    t("aiRecommendation")

            };


            displayAIResult(
                analysis
            );


            showToast(
                t("aiAnalysisCompleteToast"),
                t("issueAnalyzed")
            );

        }

        catch (error) {

            console.error(
                error
            );


            showToast(
                t("aiError"),
                t("unableToAnalyze")
            );

        }

        finally {

            analyzeIssue.disabled =
                false;


            analyzeIssue.innerHTML =
                originalHTML;


            applyTranslations();

        }

    }
);


/* =====================================================
   DEMO ISSUE DETECTION
===================================================== */

function detectIssueType(
    description
) {

    const text =
        description.toLowerCase();


    if (
        text.includes("pothole") ||
        text.includes("road") ||
        text.includes("street")
    ) {

        return t(
            "potholeRoadDamage"
        );

    }


    if (
        text.includes("light") ||
        text.includes("lamp")
    ) {

        return t(
            "streetlightIssue"
        );

    }


    if (
        text.includes("drain") ||
        text.includes("flood")
    ) {

        return t(
            "drainageFlooding"
        );

    }


    if (
        text.includes("waste") ||
        text.includes("garbage") ||
        text.includes("trash")
    ) {

        return t(
            "wasteManagement"
        );

    }


    return t(
        "civicIssue"
    );

}


/* =====================================================
   DEMO SEVERITY
===================================================== */

function detectSeverity(
    description
) {

    const text =
        description.toLowerCase();


    if (
        text.includes("danger") ||
        text.includes("accident") ||
        text.includes("flood") ||
        text.includes("blocked") ||
        text.includes("major") ||
        text.includes("large")
    ) {

        return "high";

    }


    if (
        text.includes("broken") ||
        text.includes("damage") ||
        text.includes("bad")
    ) {

        return "medium";

    }


    return "low";

}


/* =====================================================
   PRIORITY
===================================================== */

function detectPriority(
    description
) {

    const severity =
        detectSeverity(
            description
        );


    if (
        severity === "high"
    ) {

        return t(
            "urgentPriority"
        );

    }


    if (
        severity === "medium"
    ) {

        return t(
            "normalPriority"
        );

    }


    return t(
        "lowPriority"
    );

}


/* =====================================================
   DISPLAY AI RESULT
===================================================== */

function displayAIResult(
    analysis
) {

    aiResult.classList.remove(
        "hidden"
    );


    document.getElementById(
        "detectedIssue"
    ).textContent =
        analysis.issue_type;


    document.getElementById(
        "detectedSeverity"
    ).textContent =
        currentLanguage === "ur"
            ? t(
                analysis.severity === "high"
                    ? "highSeverity"
                    : analysis.severity === "medium"
                        ? "mediumSeverity"
                        : "lowSeverity"
            )
            : capitalize(
                analysis.severity
            );


    document.getElementById(
        "detectedPriority"
    ).textContent =
        analysis.priority;


    document.getElementById(
        "aiMessage"
    ).textContent =
        analysis.answer;


    const severityBadge =
        document.getElementById(
            "severityBadge"
        );


    severityBadge.textContent =
        currentLanguage === "ur"
            ? t(
                analysis.severity === "high"
                    ? "highSeverity"
                    : analysis.severity === "medium"
                        ? "mediumSeverity"
                        : "lowSeverity"
            )
            : analysis.severity.toUpperCase();


    if (
        analysis.severity === "high"
    ) {

        severityBadge.style.background =
            "#fff0f0";

        severityBadge.style.color =
            "#d94c4c";

    }

    else if (
        analysis.severity === "medium"
    ) {

        severityBadge.style.background =
            "#fff5e8";

        severityBadge.style.color =
            "#c57a28";

    }

    else {

        severityBadge.style.background =
            "#eaf9f3";

        severityBadge.style.color =
            "#249b6c";

    }


    aiResult.scrollIntoView({
        behavior: "smooth",
        block: "center"
    });

}


/* =====================================================
   SUBMIT REPORT
===================================================== */

const submitReport =
    document.getElementById(
        "submitReport"
    );


submitReport.addEventListener(
    "click",
    async () => {

        if (!capturedPhoto) {

            showToast(
                t("photoMissing"),
                t("capturePhotoFirst")
            );

            return;

        }


        const city =
            reportCity.value;


        const description =
            issueDescription.value.trim();


        if (
            !city ||
            !description
        ) {

            showToast(
                t("incompleteReport"),
                t("completeReport")
            );

            return;

        }


        submitReport.disabled =
            true;


        submitReport.innerHTML = `
            <i class="fa-solid fa-spinner fa-spin"></i>
            <span data-i18n="submitting">
                Submitting...
            </span>
        `;


        applyTranslations();


        /*
            Later:

            POST /reports

            with authenticated JWT.
        */


        await delay(1300);


        submitReport.disabled =
            false;


        submitReport.innerHTML = `
            <i class="fa-solid fa-paper-plane"></i>
            <span data-i18n="submitReport">
                Submit Report
            </span>
        `;


        applyTranslations();


        showToast(
            t("reportSubmitted"),
            t("reportSubmittedSuccessfully")
        );


        resetReport();


        setTimeout(() => {

            showPage(
                "myReports"
            );

        }, 900);

    }
);


/* =====================================================
   CLEAR REPORT
===================================================== */

const clearReport =
    document.getElementById(
        "clearReport"
    );


clearReport.addEventListener(
    "click",
    resetReport
);


function resetReport() {

    stopCamera();


    capturedPhoto = null;


    issueDescription.value =
        "";


    characterCount.textContent =
        "0";


    aiResult.classList.add(
        "hidden"
    );


    capturedImage.src =
        "";


    capturedImage.style.display =
        "none";


    cameraVideo.style.display =
        "none";


    cameraPlaceholder.style.display =
        "flex";


    cameraFrame.style.display =
        "none";


    capturePhoto.disabled =
        true;


    retakePhoto.classList.add(
        "hidden"
    );


    startCamera.innerHTML = `
        <i class="fa-solid fa-video"></i>
        <span data-i18n="startCamera">
            Start Camera
        </span>
    `;


    latitude.textContent =
        t("notDetected");


    longitude.textContent =
        t("notDetected");


    latitude.setAttribute(
        "data-i18n",
        "notDetected"
    );

    longitude.setAttribute(
        "data-i18n",
        "notDetected"
    );


    currentCoordinates = {

        latitude: null,

        longitude: null

    };


    applyTranslations();

}


/* =====================================================
   SEARCH REPORTS
===================================================== */

const reportSearch =
    document.getElementById(
        "reportSearch"
    );


const statusFilter =
    document.getElementById(
        "statusFilter"
    );


function filterReports() {

    const search =
        reportSearch.value
            .toLowerCase()
            .trim();


    const rows =
        document.querySelectorAll(
            ".reports-table .table-row"
        );


    rows.forEach(row => {

        const text =
            row.textContent.toLowerCase();


        const matchesSearch =
            !search ||
            text.includes(search);


        const matchesStatus =
            statusFilter.value === "all" ||
            text.includes(
                statusFilter.value
            );


        row.style.display =
            matchesSearch &&
            matchesStatus
                ? "grid"
                : "none";

    });

}


reportSearch.addEventListener(
    "input",
    filterReports
);


statusFilter.addEventListener(
    "change",
    filterReports
);


/* =====================================================
   NOTIFICATIONS
===================================================== */

document
    .getElementById(
        "notificationButton"
    )
    .addEventListener(
        "click",
        () => {

            showToast(
                t("notificationsTitle"),
                t("newUpdates")
            );

        }
    );


/* =====================================================
   UTILITY
===================================================== */

function delay(ms) {

    return new Promise(
        resolve =>
            setTimeout(
                resolve,
                ms
            )
    );

}


function capitalize(text) {

    if (!text) {
        return "";
    }


    return text
        .charAt(0)
        .toUpperCase() +
        text.slice(1);

}


/* =====================================================
   TOAST
===================================================== */

let toastTimer;


function showToast(
    title,
    message
) {

    toastTitle.textContent =
        title;


    toastMessage.textContent =
        message;


    toast.classList.add(
        "show"
    );


    clearTimeout(
        toastTimer
    );


    toastTimer =
        setTimeout(
            () => {

                toast.classList.remove(
                    "show"
                );

            },
            3200
        );

}


/* =====================================================
   LOAD SAVED USER
===================================================== */

function loadSavedUser() {

    const savedUser =
        localStorage.getItem(
            "civic_user"
        );


    if (!savedUser) {

        return;

    }


    try {

        const user =
            JSON.parse(
                savedUser
            );


        startApplication(
            user
        );

    }

    catch (error) {

        console.error(
            "Saved user error:",
            error
        );


        localStorage.removeItem(
            "civic_user"
        );

    }

}


/* =====================================================
   ESCAPE KEY
===================================================== */

document.addEventListener(
    "keydown",
    event => {

        if (
            event.key === "Escape"
        ) {

            closeSidebar();

        }

    }
);


/* =====================================================
   BEFORE PAGE CLOSE
===================================================== */

window.addEventListener(
    "beforeunload",
    () => {

        stopCamera();

    }
);


/* =====================================================
   INITIALIZE
===================================================== */

applyTranslations();

loadSavedUser();

