/* =====================================================
   CIVICLENS FRONTEND
===================================================== */


/* =====================================================
   CONFIGURATION
===================================================== */

const API_BASE_URL = "http://127.0.0.1:8000";


/*
   IMPORTANT:

   JWT_SECRET_KEY NEVER goes here.

   The JWT secret stays inside your backend .env file.

   The frontend should only receive/use the JWT token
   generated by the backend after successful login.
*/


/* =====================================================
   PAKISTAN CITIES
===================================================== */

const pakistanCities = [

    "Islamabad",
    "Rawalpindi",
    "Lahore",
    "Karachi",
    "Peshawar",
    "Quetta",
    "Multan",
    "Faisalabad",
    "Gujranwala",
    "Sialkot",
    "Hyderabad",
    "Bahawalpur",
    "Sargodha",
    "Sukkur",
    "Abbottabad",
    "Mardan",
    "Mingora",
    "Gujrat",
    "Jhelum",
    "Rahim Yar Khan",
    "Sahiwal",
    "Okara",
    "Wah Cantt",
    "Taxila",
    "Dera Ghazi Khan",
    "Muzaffarabad",
    "Gilgit",
    "Skardu",
    "Nawabshah",
    "Larkana",
    "Chiniot",
    "Kasur",
    "Sheikhupura",
    "Attock",
    "Nowshera",
    "Swabi",
    "Mansehra",
    "Kohat",
    "Bannu",
    "Dera Ismail Khan"

];


/* =====================================================
   ELEMENTS
===================================================== */

const authScreen =
    document.getElementById("authScreen");

const app =
    document.getElementById("app");

const loginForm =
    document.getElementById("loginForm");

const signupForm =
    document.getElementById("signupForm");

const showSignup =
    document.getElementById("showSignup");

const showLogin =
    document.getElementById("showLogin");

const loginFormElement =
    document.getElementById("loginFormElement");

const signupFormElement =
    document.getElementById("signupFormElement");

const signupCity =
    document.getElementById("signupCity");

const reportCity =
    document.getElementById("reportCity");

const sidebar =
    document.getElementById("sidebar");

const mobileMenu =
    document.getElementById("mobileMenu");

const sidebarOverlay =
    document.getElementById("sidebarOverlay");

const logoutBtn =
    document.getElementById("logoutBtn");

const userName =
    document.getElementById("userName");

const userRole =
    document.getElementById("userRole");

const userAvatar =
    document.getElementById("userAvatar");

const topAvatar =
    document.getElementById("topAvatar");

const currentCity =
    document.getElementById("currentCity");

const heroCity =
    document.getElementById("heroCity");

const cityStat =
    document.getElementById("cityStat");

const mapCityLabel =
    document.getElementById("mapCityLabel");

const toast =
    document.getElementById("toast");

const toastTitle =
    document.getElementById("toastTitle");

const toastMessage =
    document.getElementById("toastMessage");


/* =====================================================
   STATE
===================================================== */

let currentUser = null;

let currentLanguage = "en";

let cameraStream = null;

let capturedPhoto = null;

let currentCoordinates = {
    latitude: null,
    longitude: null
};


/* =====================================================
   TRANSLATIONS
===================================================== */

const translations = {

    en: {

        dashboard: "Dashboard",

        reportIssue: "Report Issue",

        myReports: "My Reports",

        map: "Issue Map",

        language: "Language",

        citizenPortal: "CITIZEN PORTAL",

        takePhoto: "Take a Photo",

        startReport: "Start Report"

    },


    ur: {

        dashboard: "ڈیش بورڈ",

        reportIssue: "مسئلہ رپورٹ کریں",

        myReports: "میری رپورٹس",

        map: "مسائل کا نقشہ",

        language: "زبان",

        citizenPortal: "شہری پورٹل",

        takePhoto: "تصویر لیں",

        startReport: "رپورٹ شروع کریں"

    }

};


/* =====================================================
   CITY DROPDOWNS
===================================================== */

function populateCities() {

    pakistanCities.forEach(city => {

        const signupOption =
            document.createElement("option");

        signupOption.value = city;

        signupOption.textContent = city;

        signupCity.appendChild(signupOption);


        const reportOption =
            document.createElement("option");

        reportOption.value = city;

        reportOption.textContent = city;

        reportCity.appendChild(reportOption);

    });

}


populateCities();


/* =====================================================
   AUTH SCREEN
===================================================== */

showSignup.addEventListener("click", () => {

    loginForm.classList.remove("active");

    signupForm.classList.add("active");

});


showLogin.addEventListener("click", () => {

    signupForm.classList.remove("active");

    loginForm.classList.add("active");

});


/* =====================================================
   PASSWORD TOGGLE
===================================================== */

document
    .querySelectorAll(".password-toggle")
    .forEach(button => {

        button.addEventListener("click", () => {

            const targetId =
                button.dataset.target;

            const input =
                document.getElementById(targetId);

            const icon =
                button.querySelector("i");


            if (input.type === "password") {

                input.type = "text";

                icon.classList.remove(
                    "fa-eye"
                );

                icon.classList.add(
                    "fa-eye-slash"
                );

            }

            else {

                input.type = "password";

                icon.classList.remove(
                    "fa-eye-slash"
                );

                icon.classList.add(
                    "fa-eye"
                );

            }

        });

    });


/* =====================================================
   SIGNUP
===================================================== */

signupFormElement.addEventListener(
    "submit",
    async (event) => {

        event.preventDefault();


        const name =
            document
                .getElementById("signupName")
                .value
                .trim();


        const email =
            document
                .getElementById("signupEmail")
                .value
                .trim();


        const password =
            document
                .getElementById("signupPassword")
                .value;


        const city =
            signupCity.value;


        if (!name || !email || !password || !city) {

            showToast(
                "Missing information",
                "Please complete all fields."
            );

            return;

        }


        /*
            TEMPORARY FRONTEND DEMO

            Later replace this with:

            fetch(`${API_BASE_URL}/auth/signup`, ...)

            Your backend will hash the password
            and create the user.
        */


        const demoUser = {

            user_id:
                "CIT-" +
                Date.now(),

            name: name,

            email: email,

            role: "citizen",

            city: city

        };


        /*
            Do NOT store passwords in localStorage.
        */


        localStorage.setItem(
            "civic_user",
            JSON.stringify(demoUser)
        );


        showToast(
            "Account created",
            "Welcome to CivicLens."
        );


        setTimeout(() => {

            startApplication(demoUser);

        }, 700);

    }
);


/* =====================================================
   LOGIN
===================================================== */

loginFormElement.addEventListener(
    "submit",
    async (event) => {

        event.preventDefault();


        const email =
            document
                .getElementById("loginEmail")
                .value
                .trim();


        const password =
            document
                .getElementById("loginPassword")
                .value;


        if (!email || !password) {

            showToast(
                "Missing information",
                "Enter your email and password."
            );

            return;

        }


        /*
            TEMPORARY DEMO LOGIN.

            Later this becomes:

            POST /auth/login

            Backend returns:

            {
                access_token: "...",
                token_type: "bearer",
                user: {...}
            }

            The JWT will be stored/managed here.

            The JWT_SECRET_KEY is NEVER stored here.
        */


        const demoUser = {

            user_id: "CIT-001",

            name: "Hamza Khan",

            email: email,

            role: "citizen",

            city: "Rawalpindi"

        };


        localStorage.setItem(
            "civic_user",
            JSON.stringify(demoUser)
        );


        showToast(
            "Login successful",
            "Welcome back to CivicLens."
        );


        setTimeout(() => {

            startApplication(demoUser);

        }, 600);

    }
);


/* =====================================================
   DEMO LOGIN
===================================================== */

const demoLogin =
    document.getElementById("demoLogin");


demoLogin.addEventListener("click", () => {

    const demoUser = {

        user_id: "CIT-DEMO",

        name: "Hamza Khan",

        email: "demo@civiclens.pk",

        role: "citizen",

        city: "Rawalpindi"

    };


    localStorage.setItem(
        "civic_user",
        JSON.stringify(demoUser)
    );


    startApplication(demoUser);

    showToast(
        "Demo Mode",
        "CivicLens demo account activated."
    );

});


/* =====================================================
   START APPLICATION
===================================================== */

function startApplication(user) {

    currentUser = user;


    authScreen.classList.add("hidden");

    app.classList.remove("hidden");


    updateUserInterface();

    showPage("dashboard");

}


/* =====================================================
   USER INTERFACE
===================================================== */

function updateUserInterface() {

    if (!currentUser) {
        return;
    }


    const name =
        currentUser.name ||
        "CivicLens User";


    const role =
        currentUser.role ||
        "citizen";


    const city =
        currentUser.city ||
        "Rawalpindi";


    userName.textContent =
        name;


    userRole.textContent =
        formatRole(role);


    const initials =
        getInitials(name);


    userAvatar.textContent =
        initials;


    topAvatar.textContent =
        initials;


    currentCity.textContent =
        city;


    heroCity.textContent =
        city;


    cityStat.textContent =
        city;


    mapCityLabel.textContent =
        city;


    reportCity.value =
        city;


    setupRoleVisibility(role);

}


/* =====================================================
   FORMAT ROLE
===================================================== */

function formatRole(role) {

    if (role === "government") {
        return "Government";
    }


    if (role === "admin") {
        return "Administrator";
    }


    return "Citizen";

}


/* =====================================================
   INITIALS
===================================================== */

function getInitials(name) {

    return name
        .split(" ")
        .map(part => part[0])
        .slice(0, 2)
        .join("")
        .toUpperCase();

}


/* =====================================================
   ROLE VISIBILITY
===================================================== */

function setupRoleVisibility(role) {

    document
        .querySelectorAll(".citizen-only")
        .forEach(element => {

            element.style.display =
                role === "citizen"
                    ? ""
                    : "none";

        });


    document
        .querySelectorAll(".government-only")
        .forEach(element => {

            element.style.display =
                role === "government"
                    ? ""
                    : "none";

        });


    document
        .querySelectorAll(".admin-only")
        .forEach(element => {

            element.style.display =
                role === "admin"
                    ? ""
                    : "none";

        });

}


/* =====================================================
   PAGE NAVIGATION
===================================================== */

const navItems =
    document.querySelectorAll(".nav-item");


navItems.forEach(item => {

    item.addEventListener("click", () => {

        const page =
            item.dataset.page;


        showPage(page);


        closeSidebar();

    });

});


document
    .querySelectorAll("[data-page-link]")
    .forEach(button => {

        button.addEventListener("click", () => {

            const page =
                button.dataset.pageLink;


            showPage(page);

        });

    });


function showPage(pageName) {

    const pages =
        document.querySelectorAll(".page");


    pages.forEach(page => {

        page.classList.remove(
            "active-page"
        );

    });


    const targetPage =
        document.getElementById(
            `${pageName}Page`
        );


    if (!targetPage) {
        return;
    }


    targetPage.classList.add(
        "active-page"
    );


    navItems.forEach(item => {

        item.classList.remove("active");


        if (
            item.dataset.page === pageName
        ) {

            item.classList.add("active");

        }

    });


    updatePageTitle(pageName);

}


/* =====================================================
   PAGE TITLE
===================================================== */

function updatePageTitle(page) {

    const title =
        document.getElementById(
            "pageTitle"
        );


    const eyebrow =
        document.getElementById(
            "pageEyebrow"
        );


    const titles = {

        dashboard: "Dashboard",

        report: "Report an Issue",

        myReports: "My Reports",

        map: "Issue Map",

        government: "Civic Operations",

        admin: "Administration"

    };


    title.textContent =
        titles[page] || "CivicLens";


    if (page === "government") {

        eyebrow.textContent =
            "GOVERNMENT PORTAL";

    }

    else if (page === "admin") {

        eyebrow.textContent =
            "SYSTEM ADMINISTRATION";

    }

    else {

        eyebrow.textContent =
            currentLanguage === "ur"
                ? "شہری پورٹل"
                : "CITIZEN PORTAL";

    }

}


/* =====================================================
   MOBILE SIDEBAR
===================================================== */

mobileMenu.addEventListener("click", () => {

    sidebar.classList.add("open");

    sidebarOverlay.classList.add("show");

});


sidebarOverlay.addEventListener(
    "click",
    closeSidebar
);


function closeSidebar() {

    sidebar.classList.remove("open");

    sidebarOverlay.classList.remove("show");

}


/* =====================================================
   LOGOUT
===================================================== */

logoutBtn.addEventListener("click", () => {

    stopCamera();


    localStorage.removeItem(
        "civic_user"
    );


    /*
        When real JWT authentication
        is connected, also remove the
        access token here.
    */


    currentUser = null;


    app.classList.add("hidden");

    authScreen.classList.remove("hidden");


    loginForm.classList.add("active");

    signupForm.classList.remove("active");


    showToast(
        "Logged out",
        "You have been signed out."
    );

});


/* =====================================================
   LANGUAGE SWITCH
===================================================== */

document
    .querySelectorAll(".language-btn")
    .forEach(button => {

        button.addEventListener(
            "click",
            () => {

                const language =
                    button.dataset.language;


                changeLanguage(language);

            }
        );

    });


function changeLanguage(language) {

    currentLanguage =
        language;


    document
        .querySelectorAll(".language-btn")
        .forEach(button => {

            button.classList.toggle(
                "active",
                button.dataset.language === language
            );

        });


    document
        .querySelectorAll("[data-i18n]")
        .forEach(element => {

            const key =
                element.dataset.i18n;


            if (
                translations[language] &&
                translations[language][key]
            ) {

                element.textContent =
                    translations[language][key];

            }

        });


    if (language === "ur") {

        document.body.classList.add(
            "rtl"
        );

    }

    else {

        document.body.classList.remove(
            "rtl"
        );

    }


    updatePageTitle(
        getCurrentPage()
    );


    showToast(
        language === "ur"
            ? "زبان تبدیل ہوگئی"
            : "Language changed",
        language === "ur"
            ? "اردو فعال ہوگئی ہے۔"
            : "English is now active."
    );

}


/* =====================================================
   GET CURRENT PAGE
===================================================== */

function getCurrentPage() {

    const active =
        document.querySelector(
            ".page.active-page"
        );


    if (!active) {
        return "dashboard";
    }


    return active.id.replace(
        "Page",
        ""
    );

}


/* =====================================================
   CAMERA
===================================================== */

const startCamera =
    document.getElementById(
        "startCamera"
    );


const capturePhoto =
    document.getElementById(
        "capturePhoto"
    );


const retakePhoto =
    document.getElementById(
        "retakePhoto"
    );


const cameraVideo =
    document.getElementById(
        "cameraVideo"
    );


const cameraCanvas =
    document.getElementById(
        "cameraCanvas"
    );


const capturedImage =
    document.getElementById(
        "capturedImage"
    );


const cameraPlaceholder =
    document.getElementById(
        "cameraPlaceholder"
    );


const cameraFrame =
    document.getElementById(
        "cameraFrame"
    );


/*
    IMPORTANT:

    There is intentionally NO:

    <input type="file">

    and NO gallery upload.

    Camera access is through getUserMedia().
*/


startCamera.addEventListener(
    "click",
    async () => {

        try {

            if (
                !navigator.mediaDevices ||
                !navigator.mediaDevices.getUserMedia
            ) {

                showToast(
                    "Camera unavailable",
                    "Your browser does not support camera access."
                );

                return;

            }


            cameraStream =
                await navigator
                    .mediaDevices
                    .getUserMedia({

                        video: {

                            facingMode: {
                                ideal: "environment"
                            }

                        },

                        audio: false

                    });


            cameraVideo.srcObject =
                cameraStream;


            cameraVideo.style.display =
                "block";


            cameraPlaceholder.style.display =
                "none";


            capturedImage.style.display =
                "none";


            cameraFrame.style.display =
                "block";


            capturePhoto.disabled =
                false;


            retakePhoto.classList.add(
                "hidden"
            );


            startCamera.innerHTML = `
                <i class="fa-solid fa-camera"></i>
                Camera Active
            `;


            showToast(
                "Camera ready",
                "Point the camera at the civic issue."
            );

        }

        catch (error) {

            console.error(
                "Camera error:",
                error
            );


            showToast(
                "Camera permission required",
                "Please allow camera access in your browser."
            );

        }

    }
);


/* =====================================================
   CAPTURE PHOTO
===================================================== */

capturePhoto.addEventListener(
    "click",
    () => {

        if (!cameraStream) {

            showToast(
                "Camera not active",
                "Start the camera first."
            );

            return;

        }


        const videoWidth =
            cameraVideo.videoWidth;


        const videoHeight =
            cameraVideo.videoHeight;


        if (!videoWidth || !videoHeight) {

            showToast(
                "Camera loading",
                "Please wait for the camera."
            );

            return;

        }


        cameraCanvas.width =
            videoWidth;


        cameraCanvas.height =
            videoHeight;


        const context =
            cameraCanvas.getContext(
                "2d"
            );


        context.drawImage(
            cameraVideo,
            0,
            0,
            videoWidth,
            videoHeight
        );


        capturedPhoto =
            cameraCanvas.toDataURL(
                "image/jpeg",
                .85
            );


        capturedImage.src =
            capturedPhoto;


        capturedImage.style.display =
            "block";


        cameraVideo.style.display =
            "none";


        cameraFrame.style.display =
            "none";


        capturePhoto.disabled =
            true;


        retakePhoto.classList.remove(
            "hidden"
        );


        stopCamera();


        showToast(
            "Photo captured",
            "Your civic issue photo is ready."
        );

    }
);


/* =====================================================
   RETAKE PHOTO
===================================================== */

retakePhoto.addEventListener(
    "click",
    async () => {

        capturedPhoto = null;


        capturedImage.style.display =
            "none";


        retakePhoto.classList.add(
            "hidden"
        );


        await startCamera.click();

    }
);


/* =====================================================
   STOP CAMERA
===================================================== */

function stopCamera() {

    if (!cameraStream) {
        return;
    }


    cameraStream
        .getTracks()
        .forEach(track => {

            track.stop();

        });


    cameraStream = null;


    if (cameraVideo) {

        cameraVideo.srcObject = null;

    }

}


/* =====================================================
   LOCATION
===================================================== */

const getLocation =
    document.getElementById(
        "getLocation"
    );


const latitude =
    document.getElementById(
        "latitude"
    );


const longitude =
    document.getElementById(
        "longitude"
    );


const mapMarker =
    document.getElementById(
        "mapMarker"
    );


getLocation.addEventListener(
    "click",
    () => {

        if (!navigator.geolocation) {

            showToast(
                "Location unavailable",
                "Your browser does not support location."
            );

            return;

        }


        getLocation.innerHTML = `
            <i class="fa-solid fa-spinner fa-spin"></i>
            Detecting Location...
        `;


        navigator.geolocation.getCurrentPosition(

            position => {

                currentCoordinates.latitude =
                    position.coords.latitude;


                currentCoordinates.longitude =
                    position.coords.longitude;


                latitude.textContent =
                    currentCoordinates.latitude.toFixed(6);


                longitude.textContent =
                    currentCoordinates.longitude.toFixed(6);


                mapMarker.style.left =
                    "50%";


                mapMarker.style.top =
                    "50%";


                getLocation.innerHTML = `
                    <i class="fa-solid fa-location-dot"></i>
                    Location Detected
                `;


                showToast(
                    "Location detected",
                    "Your current location has been captured."
                );

            },


            error => {

                console.error(
                    "Location error:",
                    error
                );


                getLocation.innerHTML = `
                    <i class="fa-solid fa-crosshairs"></i>
                    Use My Current Location
                `;


                showToast(
                    "Location permission required",
                    "Please allow location access."
                );

            },

            {

                enableHighAccuracy: true,

                timeout: 10000,

                maximumAge: 0

            }

        );

    }
);


/* =====================================================
   DESCRIPTION COUNTER
===================================================== */

const issueDescription =
    document.getElementById(
        "issueDescription"
    );


const characterCount =
    document.getElementById(
        "characterCount"
    );


issueDescription.addEventListener(
    "input",
    () => {

        if (
            issueDescription.value.length > 500
        ) {

            issueDescription.value =
                issueDescription.value.substring(
                    0,
                    500
                );

        }


        characterCount.textContent =
            issueDescription.value.length;

    }
);


/* =====================================================
   AI ANALYSIS
===================================================== */

const analyzeIssue =
    document.getElementById(
        "analyzeIssue"
    );


const aiResult =
    document.getElementById(
        "aiResult"
    );


analyzeIssue.addEventListener(
    "click",
    async () => {

        const description =
            issueDescription.value.trim();


        if (!capturedPhoto) {

            showToast(
                "Photo required",
                "Take a photo before analyzing the issue."
            );

            return;

        }


        if (!reportCity.value) {

            showToast(
                "City required",
                "Please select your city."
            );

            return;

        }


        if (!description) {

            showToast(
                "Description required",
                "Describe the civic issue first."
            );

            return;

        }


        const originalHTML =
            analyzeIssue.innerHTML;


        analyzeIssue.disabled =
            true;


        analyzeIssue.innerHTML = `
            <i class="fa-solid fa-spinner fa-spin"></i>
            Analyzing...
        `;


        /*
            REAL BACKEND CONNECTION:

            Your existing backend already has:

            POST /issues/analyze

            We will connect this properly after
            confirming the exact request schema.

            The following demo response allows
            the frontend workflow to be tested now.
        */


        try {

            /*
                TEMPORARY DEMO DELAY
            */

            await delay(1600);


            const analysis = {

                issue_type:
                    detectIssueType(description),

                severity:
                    detectSeverity(description),

                priority:
                    detectPriority(description),

                answer:
                    "CivicLens AI has analyzed the submitted issue and recommends that the relevant municipal department review it."

            };


            displayAIResult(
                analysis
            );


            showToast(
                "AI analysis complete",
                "The issue has been analyzed successfully."
            );

        }

        catch (error) {

            console.error(
                error
            );


            showToast(
                "AI error",
                "Unable to analyze the issue."
            );

        }

        finally {

            analyzeIssue.disabled =
                false;


            analyzeIssue.innerHTML =
                originalHTML;

        }

    }
);


/* =====================================================
   DEMO ISSUE DETECTION
===================================================== */

function detectIssueType(
    description
) {

    const text =
        description.toLowerCase();


    if (
        text.includes("pothole") ||
        text.includes("road") ||
        text.includes("street")
    ) {

        return "Pothole / Road Damage";

    }


    if (
        text.includes("light") ||
        text.includes("lamp")
    ) {

        return "Streetlight";

    }


    if (
        text.includes("drain") ||
        text.includes("flood")
    ) {

        return "Drainage / Flooding";

    }


    if (
        text.includes("waste") ||
        text.includes("garbage") ||
        text.includes("trash")
    ) {

        return "Waste Management";

    }


    return "Civic Issue";

}


/* =====================================================
   DEMO SEVERITY
===================================================== */

function detectSeverity(
    description
) {

    const text =
        description.toLowerCase();


    if (
        text.includes("danger") ||
        text.includes("accident") ||
        text.includes("flood") ||
        text.includes("blocked") ||
        text.includes("major") ||
        text.includes("large")
    ) {

        return "high";

    }


    if (
        text.includes("broken") ||
        text.includes("damage") ||
        text.includes("bad")
    ) {

        return "medium";

    }


    return "low";

}


/* =====================================================
   PRIORITY
===================================================== */

function detectPriority(
    description
) {

    const severity =
        detectSeverity(
            description
        );


    if (severity === "high") {

        return "Urgent";

    }


    if (severity === "medium") {

        return "Normal";

    }


    return "Low";

}


/* =====================================================
   DISPLAY AI RESULT
===================================================== */

function displayAIResult(
    analysis
) {

    aiResult.classList.remove(
        "hidden"
    );


    document.getElementById(
        "detectedIssue"
    ).textContent =
        analysis.issue_type;


    document.getElementById(
        "detectedSeverity"
    ).textContent =
        capitalize(
            analysis.severity
        );


    document.getElementById(
        "detectedPriority"
    ).textContent =
        analysis.priority;


    document.getElementById(
        "aiMessage"
    ).textContent =
        analysis.answer;


    const severityBadge =
        document.getElementById(
            "severityBadge"
        );


    severityBadge.textContent =
        analysis.severity
            .toUpperCase();


    if (
        analysis.severity === "high"
    ) {

        severityBadge.style.background =
            "#fff0f0";

        severityBadge.style.color =
            "#d94c4c";

    }

    else if (
        analysis.severity === "medium"
    ) {

        severityBadge.style.background =
            "#fff5e8";

        severityBadge.style.color =
            "#c57a28";

    }

    else {

        severityBadge.style.background =
            "#eaf9f3";

        severityBadge.style.color =
            "#249b6c";

    }


    aiResult.scrollIntoView({
        behavior: "smooth",
        block: "center"
    });

}


/* =====================================================
   SUBMIT REPORT
===================================================== */

const submitReport =
    document.getElementById(
        "submitReport"
    );


submitReport.addEventListener(
    "click",
    async () => {

        if (!capturedPhoto) {

            showToast(
                "Photo missing",
                "Capture an issue photo first."
            );

            return;

        }


        const city =
            reportCity.value;


        const description =
            issueDescription.value.trim();


        if (!city || !description) {

            showToast(
                "Incomplete report",
                "Please complete the report."
            );

            return;

        }


        submitReport.disabled =
            true;


        submitReport.innerHTML = `
            <i class="fa-solid fa-spinner fa-spin"></i>
            Submitting...
        `;


        /*
            Later:

            POST /reports

            with authenticated JWT:

            Authorization:
            Bearer <access_token>
        */


        await delay(1300);


        submitReport.disabled =
            false;


        submitReport.innerHTML = `
            <i class="fa-solid fa-paper-plane"></i>
            Submit Report
        `;


        showToast(
            "Report submitted",
            "Your civic report has been submitted successfully."
        );


        resetReport();


        setTimeout(() => {

            showPage(
                "myReports"
            );

        }, 900);

    }
);


/* =====================================================
   CLEAR REPORT
===================================================== */

const clearReport =
    document.getElementById(
        "clearReport"
    );


clearReport.addEventListener(
    "click",
    resetReport
);


function resetReport() {

    stopCamera();


    capturedPhoto = null;


    issueDescription.value =
        "";


    characterCount.textContent =
        "0";


    aiResult.classList.add(
        "hidden"
    );


    capturedImage.src =
        "";


    capturedImage.style.display =
        "none";


    cameraVideo.style.display =
        "none";


    cameraPlaceholder.style.display =
        "flex";


    cameraFrame.style.display =
        "none";


    capturePhoto.disabled =
        true;


    retakePhoto.classList.add(
        "hidden"
    );


    startCamera.innerHTML = `
        <i class="fa-solid fa-video"></i>
        Start Camera
    `;


    latitude.textContent =
        "Not detected";


    longitude.textContent =
        "Not detected";


    currentCoordinates = {

        latitude: null,

        longitude: null

    };

}


/* =====================================================
   SEARCH REPORTS
===================================================== */

const reportSearch =
    document.getElementById(
        "reportSearch"
    );


const statusFilter =
    document.getElementById(
        "statusFilter"
    );


function filterReports() {

    const search =
        reportSearch.value
            .toLowerCase()
            .trim();


    const rows =
        document.querySelectorAll(
            ".reports-table .table-row"
        );


    rows.forEach(row => {

        const text =
            row.textContent.toLowerCase();


        const matchesSearch =
            !search ||
            text.includes(search);


        const matchesStatus =
            statusFilter.value === "all" ||
            text.includes(
                statusFilter.value
            );


        row.style.display =
            matchesSearch &&
            matchesStatus
                ? "grid"
                : "none";

    });

}


reportSearch.addEventListener(
    "input",
    filterReports
);


statusFilter.addEventListener(
    "change",
    filterReports
);


/* =====================================================
   NOTIFICATIONS
===================================================== */

document
    .getElementById(
        "notificationButton"
    )
    .addEventListener(
        "click",
        () => {

            showToast(
                "Notifications",
                "You have 3 new CivicLens updates."
            );

        }
    );


/* =====================================================
   UTILITY
===================================================== */

function delay(ms) {

    return new Promise(
        resolve =>
            setTimeout(
                resolve,
                ms
            )
    );

}


function capitalize(text) {

    if (!text) {
        return "";
    }


    return text
        .charAt(0)
        .toUpperCase() +
        text.slice(1);

}


/* =====================================================
   TOAST
===================================================== */

let toastTimer;


function showToast(
    title,
    message
) {

    toastTitle.textContent =
        title;


    toastMessage.textContent =
        message;


    toast.classList.add(
        "show"
    );


    clearTimeout(
        toastTimer
    );


    toastTimer =
        setTimeout(
            () => {

                toast.classList.remove(
                    "show"
                );

            },
            3200
        );

}


/* =====================================================
   LOAD SAVED USER
===================================================== */

function loadSavedUser() {

    const savedUser =
        localStorage.getItem(
            "civic_user"
        );


    if (!savedUser) {
        return;
    }


    try {

        const user =
            JSON.parse(
                savedUser
            );


        startApplication(
            user
        );

    }

    catch (error) {

        console.error(
            "Saved user error:",
            error
        );


        localStorage.removeItem(
            "civic_user"
        );

    }

}


/* =====================================================
   ESCAPE KEY
===================================================== */

document.addEventListener(
    "keydown",
    event => {

        if (
            event.key === "Escape"
        ) {

            closeSidebar();

        }

    }
);


/* =====================================================
   BEFORE PAGE CLOSE
===================================================== */

window.addEventListener(
    "beforeunload",
    () => {

        stopCamera();

    }
);


/* =====================================================
   INITIALIZE
===================================================== */

loadSavedUser();